### ISSUE TITLE
Issue evaluating hashtable on default mappings config

### ISSUE THREAD

**Issue by thatnerdjosh** [emacs-lsp/lsp-docker#82] opened 2023-11-17 02:44 UTC
I was having trouble registering a custom image/dockerfile as an LSP server following the GitHub readme...

After about 5h of debugging, I found out the issue was because I was happy with the default mappings and tried using them.

There is some issue where the hashtable in the list of mappings (below) is not evaluated:

```lisp
(defcustom lsp-docker-persistent-default-config
  (ht ('server (ht ('type "docker")
                   ('subtype "image")
                   ('name "emacslsp/lsp-docker-langservers")
                   ('server nil)
                   ('launch_command nil)))
      ('mappings [
                  (ht ('source ".")
                      ('destination "/projects"))
                  ]))
  "Default configuration for all language servers with persistent configurations"
  :type 'hash-table
  :group 'lsp-docker
)
```

This is seen when printing the hashtable via an interactive function:

```lisp
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (server #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (launch_command "blah" server "custom-lsp" name "custom-lsp" subtype "image" type "docker")) mappings [(ht ('source ".") ('destination "/projects"))]))
```

I would fix this, but it may be quicker for you, as I am not experienced with development of elisp plugins.

If you can point me in the right direction for setting up my environment to work on an elisp plugin, I can fix it and create a PR.

**Comment by thatnerdjosh** [comment] 2023-11-17 06:25
Here is the error I was running into:

`condition-case: Wrong type argument: hash-table-p, (ht ('source ".") ('destination "/projects")) [2 times]`

**Comment by thatnerdjosh** [comment] 2023-11-17 15:51
cc: @rnikoopour

**Comment by factyy** [comment] 2023-11-17 16:03
This feature was written by me but I'm really out of time right now :(
Could you give it a try first?

**Comment by yyoncho** [comment] 2023-11-17 16:11
I pushed a fix for the ht usage: https://github.com/emacs-lsp/lsp-docker/commit/a9beb0b5c3cdb3fb1b6e34c6ad752f3b8474ae8a . Not sure if this will be enough to unblock the issue.

**Comment by thatnerdjosh** [comment] 2023-11-17 16:34
Seems to work :)

**Comment by thatnerdjosh** [comment] 2023-11-18 12:17
Thanks @yyoncho - closing the issue now.

**Closed** 2023-11-18 12:17 UTC

**Comment by Wilfred** [comment] 2023-11-18 19:36
FWIW the problem is how you're using a vector `[]` literal syntax for `mappings`. Vector elements in literals aren't evaluated.

```
ELISP> [(+ 1 2)]
[(+ 1 2)]

ELISP> (vector (+ 1 2))
[3]
```

**Comment by thatnerdjosh** [comment] 2023-11-19 01:30
@Wilfred - good to know - thanks!

@yyoncho - if you want I can submit a pull request which changes it to not use a vector literal instead of changing the library/method for creating the mapping. It works fine as is, just let me know.

**Comment by factyy** [comment] 2023-11-19 17:21
@Wilfred , thanks a lot! To be honest I just wasn't aware of this when was implementing this feature. My bad :/
